# Generated by Django 4.2.5 on 2024-01-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
